### Get all puzzles
GET localhost:8080/mars-landing/puzzles
Accept: application/json

### Get the specified puzzle
GET localhost:8080/mars-landing/puzzles/1

### Start a simulation
POST localhost:8080/mars-landing/simulations
Accept: text/plain
Content-Type: application/json

{
  "globalSettings": {
    "limitType": "TIME",
    "limitValue": 2000,
    "chromosomeSize": 100,
    "populationSize": 100,
    "mutationProbability": 0.2,
    "elitismPercent": 0.2,
    "selectionType": "RANDOM",
    "crossoverType": "BLEND",
    "mutationType": "PER_GENE"
  },
  "engineSettings": {
    "puzzleId": 1,
    "speedMax": 100,
    "xSpeedWeight": 50,
    "ySpeedWeight": 50,
    "rotateWeight": 10,
    "distanceWeight": 250,
    "crashSpeedWeight": 0.9
  }
}

### Start a simulation (tournament selection)
POST localhost:8080/mars-landing/simulations
Accept: text/plain
Content-Type: application/json

{
  "globalSettings": {
    "limitType": "TIME",
    "limitValue": 2000,
    "chromosomeSize": 100,
    "populationSize": 100,
    "mutationProbability": 0.2,
    "elitismPercent": 0.2,
    "selectionType": "TOURNAMENT",
    "crossoverType": "BLEND",
    "mutationType": "PER_GENE"
  },
  "engineSettings": {
    "puzzleId": 1,
    "speedMax": 100,
    "xSpeedWeight": 50,
    "ySpeedWeight": 50,
    "rotateWeight": 10,
    "distanceWeight": 250,
    "crashSpeedWeight": 0.9
  }
}

### Get all simulation summaries
GET localhost:8080/mars-landing/simulations

### Get the specified simulation summary
GET localhost:8080/mars-landing/simulations/0

### Delete the specified simulation
DELETE localhost:8080/mars-landing/simulations/0

### Get all generations for the specified simulation
GET localhost:8080/mars-landing/simulations/0/generations

### Get a specific generation for the specified simulation
GET localhost:8080/mars-landing/simulations/0/generations/0

### Start a benchmark
POST localhost:8080/mars-landing/benchmarks
Accept: text/plain
Content-Type: application/json

{
  "puzzlesId": [1, 2],
  "runCount": 2,
  "globalSettings": {
    "limitType": "TIME",
    "limitValue": 2000,
    "chromosomeSize": 100,
    "populationSize": 100,
    "mutationProbability": 0.2,
    "elitismPercent": 0.2,
    "selectionType": "RANDOM",
    "crossoverType": "BLEND",
    "mutationType": "PER_GENE"
  },
  "engineSettings": {
    "puzzleId": 1,
    "speedMax": 100,
    "xSpeedWeight": 50,
    "ySpeedWeight": 50,
    "rotateWeight": 10,
    "distanceWeight": 250,
    "crashSpeedWeight": 0.9
  }
}

### Get all benchmark results
GET localhost:8080/mars-landing/benchmarks

### Get the specified benchmark result
GET localhost:8080/mars-landing/benchmarks/0

### Delete the specified benchmark (409 if still running)
DELETE localhost:8080/mars-landing/benchmarks/0

### Reset DB (deletes all simulations and benchmarks)
POST localhost:8080/admin/reset
